### PR TITLE
fix(andOperator): implement checking of nested Either

### LINKED ISSUE #8: tapF bug
tapF method resolves even though it contains Either.left

The following code illustrates the issue:

```javascript
const { FlutureTMonetEither: FTE } = require('monad-t')

FTE.fromValue('hello')
  .tapF(() => FTE
    .fromValue(0)
    .filter(v => v === 1, 'sad')
  )
  .promise()
  .then(console.log)
  .catch(console.log)

// Prints 'hello' instead of 'sad'
```

### PR DESCRIPTION
**Pull request by michaelkuk**
Fixes #8

### CODE REVIEW

**Review by Cheprer — APPROVED** [review]
describe -> and, tapF v unit testech jinak ok

File: src/FlutureTMonetEither/index.js [hunk 1]
```diff
@@ -366,7 +366,14 @@ FlutureTMonetEither.prototype.fork = function fork(leftFn, rightFn) {
  */
 FlutureTMonetEither.prototype.and = function and(futureEither) {
   return this.constructor.of(
-    this.run.and(futureEither.run)
+    Future.of(curry((e1, e2) => {
```
Comment (char0n) [inline src/FlutureTMonetEither/index.js]: LGTM
The only optimization in this case is that I would use native currying here to remove surrogate `curry` overhead
```javascript
Future.of(either1 => either2 => {
...
});

File: src/FlutureTMonetEither/index.js [hunk 2]
```diff
@@ -366,7 +366,14 @@ FlutureTMonetEither.prototype.fork = function fork(leftFn, rightFn) {
...
+      if (e1.isLeft()) {
```
Comment (char0n) [inline src/FlutureTMonetEither/index.js]: I would use monadic bind here and let Either deal with the binding implicitly. The if statements and this should be equivalent.
```javascript
Future
  .of(either1 => either2 => either1.chain(always(either2)
  .ap(this.run)
  .ap(futureEither.run)
```

**Review by char0n — APPROVED** [review]
